- server/wiselife/src/main/java/be/wiselife/WiselifeApplication.java
- server/wiselife/src/main/java/be/wiselife/aop/DiscordWebhook.java
- server/wiselife/src/main/java/be/wiselife/aop/GlobalExceptionAdvice.java
- server/wiselife/src/main/java/be/wiselife/audit/TimeAudit.java
- server/wiselife/src/main/java/be/wiselife/audit/WriterAudit.java
- server/wiselife/src/main/java/be/wiselife/dto/ErrorResponse.java
- server/wiselife/src/main/java/be/wiselife/dto/ErrorResponseDto.java
- server/wiselife/src/main/java/be/wiselife/dto/MultiResponseDto.java
- server/wiselife/src/main/java/be/wiselife/dto/PageInfo.java
- server/wiselife/src/main/java/be/wiselife/dto/SingleResponseDto.java
- server/wiselife/src/main/java/be/wiselife/exception/BusinessLogicException.java
- server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
- server/wiselife/src/main/java/be/wiselife/member/controller/MemberController.java
- server/wiselife/src/main/java/be/wiselife/member/dto/MemberDto.java
- server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
- server/wiselife/src/main/java/be/wiselife/member/mapper/MemberMapper.java
- server/wiselife/src/main/java/be/wiselife/member/repository/MemberRepository.java
- server/wiselife/src/main/java/be/wiselife/member/service/MemberService.java
> feat: Member 엔티티 기본기능 구현

- server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
- server/wiselife/src/main/java/be/wiselife/order/controller/OrderController.java
- server/wiselife/src/main/java/be/wiselife/order/dto/OrderDto.java
- server/wiselife/src/main/java/be/wiselife/order/entity/Order.java
- server/wiselife/src/main/java/be/wiselife/order/mapper/OrderMapper.java
- server/wiselife/src/main/java/be/wiselife/order/service/OrderService.java
- server/wiselife/src/main/java/be/wiselife/security/JwtTokenizer.java
- server/wiselife/src/main/java/be/wiselife/security/service/OauthService.java
fix: Jwt Token fixed, order is still fixing
> fix: Jwt Token fixed, order is still fixing

- server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
- server/wiselife/src/main/java/be/wiselife/follow/controller/FollowController.java
- server/wiselife/src/main/java/be/wiselife/follow/entity/Follow.java
- server/wiselife/src/main/java/be/wiselife/follow/service/FollowService.java
- server/wiselife/src/main/java/be/wiselife/image/entity/Image.java
- server/wiselife/src/main/java/be/wiselife/member/controller/MemberController.java
- server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
- server/wiselife/src/main/java/be/wiselife/member/service/MemberService.java
- server/wiselife/src/main/java/be/wiselife/security/JwtTokenizer.java
feat: 팔로워 조작, 회원 조회, 회원 수정에 로그인 검증 추가
> feat: 팔로워 조작, 회원 조회, 회원 수정에 로그인 검증 추가

- server/wiselife/src/main/java/be/wiselife/audit/TimeAudit.java
- server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
- server/wiselife/src/main/java/be/wiselife/member/dto/MemberDto.java
- server/wiselife/src/main/java/be/wiselife/order/controller/OrderController.java
- server/wiselife/src/main/java/be/wiselife/order/dto/OrderDto.java
- server/wiselife/src/main/java/be/wiselife/order/entity/Order.java
- server/wiselife/src/main/java/be/wiselife/order/mapper/OrderMapper.java
- server/wiselife/src/main/java/be/wiselife/order/repository/OrderRepository.java
- server/wiselife/src/main/java/be/wiselife/order/service/OrderService.java
- server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepository.java
- server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepositoryImpl.java
- server/wiselife/src/main/java/be/wiselife/security/JwtTokenizer.java
> fix: order logic

- .idea/compiler.xml
- server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
- server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
- server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
- server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
- server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
- server/wiselife/src/main/java/be/wiselife/challengetalk/controller/ChallengeTalkController.java
- server/wiselife/src/main/java/be/wiselife/challengetalk/dto/ChallengeTalkDto.java
- server/wiselife/src/main/java/be/wiselife/challengetalk/entity/ChallengeTalk.java
- server/wiselife/src/main/java/be/wiselife/challengetalk/mapper/ChallengeTalkMapper.java
- server/wiselife/src/main/java/be/wiselife/challengetalk/repository/ChallengeTalkRepository.java
- server/wiselife/src/main/java/be/wiselife/challengetalk/service/ChallengeTalkService.java
- server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
- server/wiselife/src/main/java/be/wiselife/member/service/MemberService.java
- server/wiselife/src/main/java/be/wiselife/security/JwtTokenizer.java
feat: 챌린지 상세페이지 조회 댓글 출력 기능 추가
> feat: 챌린지 상세페이지 조회 댓글 출력 기능 추가

- server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
- server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
- server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
- server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
- server/wiselife/src/main/java/be/wiselife/image/entity/ChallengeCertImage.java
- server/wiselife/src/main/java/be/wiselife/image/entity/ChallengeExamImage.java
- server/wiselife/src/main/java/be/wiselife/image/entity/ChallengeRepImage.java
- server/wiselife/src/main/java/be/wiselife/image/entity/Image.java
- server/wiselife/src/main/java/be/wiselife/image/entity/MemberImage.java
- server/wiselife/src/main/java/be/wiselife/image/entity/ReviewImage.java
- server/wiselife/src/main/java/be/wiselife/image/repository/ImageRepository.java
- server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
- server/wiselife/src/main/java/be/wiselife/member/dto/MemberDto.java
- server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
- server/wiselife/src/main/java/be/wiselife/member/mapper/MemberMapper.java
- server/wiselife/src/main/java/be/wiselife/member/service/MemberService.java
- server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepository.java
- server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepositoryImpl.java
- server/wiselife/src/main/java/be/wiselife/security/JwtTokenizer.java
- server/wiselife/src/main/java/be/wiselife/security/service/OauthService.java
feat: 멤버 프로필 사진 등록 로직 구현
feat: 챌린지 대표사진 등록 로직 구현
> feat: 멤버 프로필 사진 등록 로직 구현

- server/wiselife/build.gradle
- server/wiselife/src/main/java/be/wiselife/member/controller/MemberController.java
- server/wiselife/src/main/java/be/wiselife/order/controller/OrderController.java
- server/wiselife/src/main/java/be/wiselife/order/mapper/OrderMapper.java
- server/wiselife/src/main/java/be/wiselife/order/service/OrderService.java
- server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepositoryImpl.java
- server/wiselife/src/main/java/be/wiselife/security/JwtTokenizer.java
- server/wiselife/src/main/java/be/wiselife/security/SecurityConfiguration.java
- server/wiselife/src/main/java/be/wiselife/security/controller/OauthController.java
- server/wiselife/src/main/java/be/wiselife/security/filter/MemberAuthenticationEntryPoint.java
- server/wiselife/src/main/java/be/wiselife/security/principal/OAuth2MemberInfo.java
- server/wiselife/src/main/java/be/wiselife/security/service/OauthService.java
- server/wiselife/src/main/resources/application.yml
- server/wiselife/src/main/resources/file-info-appender.xml
- server/wiselife/src/main/resources/firebase/wiselife-6e33f-firebase-adminsdk-ibzyg-20b00f1642.json
- server/wiselife/src/main/resources/logback-spring.xml
> docs: order, security 주석정리

- server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
- server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
- server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
- server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
- server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
- server/wiselife/src/main/java/be/wiselife/challengereview/controller/ChallengeReviewController.java
- server/wiselife/src/main/java/be/wiselife/challengereview/dto/ChallengeReviewDto.java
- server/wiselife/src/main/java/be/wiselife/challengereview/entity/ChallengeReview.java
- server/wiselife/src/main/java/be/wiselife/challengereview/mapper/ChallengeReviewMapper.java
- server/wiselife/src/main/java/be/wiselife/challengereview/repository/ChallengeReviewRepository.java
- server/wiselife/src/main/java/be/wiselife/challengereview/service/ChallengeReviewService.java
- server/wiselife/src/main/java/be/wiselife/challengetalk/controller/ChallengeTalkController.java
- server/wiselife/src/main/java/be/wiselife/challengetalk/entity/ChallengeTalk.java
- server/wiselife/src/main/java/be/wiselife/challengetalk/service/ChallengeTalkService.java
- server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
- server/wiselife/src/main/java/be/wiselife/member/service/MemberService.java
- server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepositoryImpl.java
> feat: 챌린지 후기 생성, 수정 구현

- server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
- server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
- server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
- server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
- server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
- server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
- server/wiselife/src/main/java/be/wiselife/image/entity/ChallengeCertImage.java
- server/wiselife/src/main/java/be/wiselife/image/entity/ChallengeExamImage.java
- server/wiselife/src/main/java/be/wiselife/image/entity/ChallengeRepImage.java
- server/wiselife/src/main/java/be/wiselife/image/entity/Image.java
- server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
- server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
- server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepository.java
- server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepositoryImpl.java
feat: 챌린지 예시 사진 등록 로직 구현
feat: 챌린지 예시 사진 수정 로직 구현
> feat: 챌린지 예시 사진 등록 로직 구현

- server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
- server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
- server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
- server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
- server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
- server/wiselife/src/main/java/be/wiselife/challengereview/controller/ChallengeReviewController.java
- server/wiselife/src/main/java/be/wiselife/challengereview/entity/ChallengeReview.java
- server/wiselife/src/main/java/be/wiselife/challengereview/service/ChallengeReviewService.java
- server/wiselife/src/main/java/be/wiselife/challengetalk/entity/ChallengeTalk.java
- server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
- server/wiselife/src/main/java/be/wiselife/image/entity/ChallengeCertImage.java
- server/wiselife/src/main/java/be/wiselife/image/entity/Image.java
- server/wiselife/src/main/java/be/wiselife/image/entity/ReviewImage.java
- server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
- server/wiselife/src/main/java/be/wiselife/member/dto/MemberDto.java
- server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
- server/wiselife/src/main/java/be/wiselife/member/mapper/MemberMapper.java
- server/wiselife/src/main/java/be/wiselife/memberchallenge/entity/MemberChallenge.java
- server/wiselife/src/main/java/be/wiselife/memberchallenge/repository/MemberChallengeRepository.java
- server/wiselife/src/main/java/be/wiselife/memberchallenge/service/MemberChallengeService.java
- server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepository.java
- server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepositoryImpl.java
feat : 챌린지 참가 기능 추가
feat : 리뷰사진 등록 및 수정 기능 추가
feat : 챌린지 조회시 로그인된 유저는 자신이 인증한 사진만 볼수있게, 로그인 안된 사람은 인증사진을 볼수 없게 구현
feat : 인증가능시간 중 각 인증시간에 등록한 사진만 수정가능하게 구현 추가
feat : 인증사진 등록 및 해당일자의 인증 횟수 탐색 기능 구현
> feat : 챌린지 참가 기능 추가

- server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
- server/wiselife/src/main/java/be/wiselife/security/JwtTokenizer.java
- server/wiselife/src/main/java/be/wiselife/security/SecurityConfiguration.java
- server/wiselife/src/main/java/be/wiselife/security/controller/TokenController.java
- server/wiselife/src/main/java/be/wiselife/security/filter/JwtVerificationFilter.java
- server/wiselife/src/main/java/be/wiselife/security/service/OauthService.java
- server/wiselife/src/main/java/be/wiselife/security/utils/CustomAuthorityUtils.java
- server/wiselife/src/main/resources/application.yml
> fix: fixing cors error

- server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
- server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
- server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
- server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
- server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
- server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
- server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
- server/wiselife/src/main/java/be/wiselife/memberchallenge/repository/MemberChallengeRepository.java
- server/wiselife/src/main/java/be/wiselife/memberchallenge/service/MemberChallengeService.java
- server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepository.java
- server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepositoryImpl.java
feat: 멤버의 챌린지 성공률 표시되게 구현
feat: 멤버가 챌린지 참여시 챌린지 참여인원 수 증가
> feat: 멤버의 챌린지 성공률 표시되게 구현

- server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
- server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
- server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
- server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
- server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
- server/wiselife/src/main/java/be/wiselife/challengereview/controller/ChallengeReviewController.java
- server/wiselife/src/main/java/be/wiselife/challengereview/dto/ChallengeReviewDto.java
- server/wiselife/src/main/java/be/wiselife/challengereview/entity/ChallengeReview.java
- server/wiselife/src/main/java/be/wiselife/challengereview/repository/ChallengeReviewRepository.java
- server/wiselife/src/main/java/be/wiselife/challengereview/service/ChallengeReviewService.java
- server/wiselife/src/main/java/be/wiselife/challengetalk/controller/ChallengeTalkController.java
- server/wiselife/src/main/java/be/wiselife/challengetalk/dto/ChallengeTalkDto.java
- server/wiselife/src/main/java/be/wiselife/challengetalk/entity/ChallengeTalk.java
- server/wiselife/src/main/java/be/wiselife/challengetalk/service/ChallengeTalkService.java
- server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
- server/wiselife/src/main/java/be/wiselife/member/service/MemberService.java
- server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepositoryImpl.java
> feat: jwt 권한 이용한 crud 허용 기능

- server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
- server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
- server/wiselife/src/main/java/be/wiselife/security/SecurityConfiguration.java
> fix: conflict codes

- server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
- server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
- server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
- server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
- server/wiselife/src/main/java/be/wiselife/dummy/DummyService.java
- server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
- server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
- server/wiselife/src/main/java/be/wiselife/member/dto/MemberDto.java
- server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
- server/wiselife/src/main/java/be/wiselife/member/mapper/MemberMapper.java
- server/wiselife/src/main/java/be/wiselife/member/service/MemberService.java
- server/wiselife/src/main/java/be/wiselife/memberchallenge/service/MemberChallengeService.java
- server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepository.java
- server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepositoryImpl.java
> feat: 멤버챌린지 개인성공률 구현

- server/wiselife/src/main/java/be/wiselife/dummy/DummyService.java
- server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
- server/wiselife/src/main/java/be/wiselife/security/controller/TokenController.java
> fix: dummy data

- server/wiselife/src/main/java/be/wiselife/dto/MultiResponseDto.java
- server/wiselife/src/main/java/be/wiselife/dummy/DummyService.java
- server/wiselife/src/main/java/be/wiselife/order/controller/OrderController.java
fix: dummy data & order singleDTO
> fix: dummy data & order singleDTO

- server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
- server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
- server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
- server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
- server/wiselife/src/main/java/be/wiselife/challenge/repository/ChallengeRepository.java
- server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
- server/wiselife/src/main/java/be/wiselife/challengereview/controller/ChallengeReviewController.java
- server/wiselife/src/main/java/be/wiselife/challengereview/service/ChallengeReviewService.java
- server/wiselife/src/main/java/be/wiselife/challengetalk/service/ChallengeTalkService.java
- server/wiselife/src/main/java/be/wiselife/dummy/DummyService.java
- server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
- server/wiselife/src/main/java/be/wiselife/memberchallenge/entity/MemberChallenge.java
feat: 챌린지 리뷰 삭제 수정 & 챌린지 검색 자동완성 기능 + 챌린지 검색 기능
> fix: 챌린지 리뷰 삭제 수정 & feat: 챌린지 검색 자동완성 기능 + 챌린지 검색 기능

- server/wiselife/build.gradle
- server/wiselife/src/main/java/be/wiselife/dto/AmountResponseDto.java
- server/wiselife/src/main/java/be/wiselife/dto/MultiResponseDto.java
- server/wiselife/src/main/java/be/wiselife/image/config/imageConfig.java
- server/wiselife/src/main/java/be/wiselife/member/controller/MemberController.java
- server/wiselife/src/main/java/be/wiselife/member/repository/MemberRepository.java
- server/wiselife/src/main/java/be/wiselife/member/service/MemberService.java
- server/wiselife/src/main/java/be/wiselife/order/controller/OrderController.java
- server/wiselife/src/main/java/be/wiselife/order/service/OrderService.java
- server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepository.java
- server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepositoryImpl.java
- server/wiselife/src/main/java/be/wiselife/security/service/OauthService.java
- server/wiselife/src/main/resources/application-oauth.yml
- server/wiselife/src/main/resources/application.yml
feat: search member controller
> feat: search member controller

- server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
- server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
- server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
- server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
- server/wiselife/src/main/java/be/wiselife/dummy/DummyService.java
- server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
- server/wiselife/src/main/java/be/wiselife/member/dto/MemberDto.java
- server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
- server/wiselife/src/main/java/be/wiselife/member/mapper/MemberMapper.java
- server/wiselife/src/main/java/be/wiselife/memberchallenge/entity/MemberChallenge.java
- server/wiselife/src/main/java/be/wiselife/memberchallenge/service/MemberChallengeService.java
- server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepositoryImpl.java
feat: 레벨업 기능 구현
fix: 멤버 챌린지 내 개인 성공률 로직 변경, 마이페이지 내 챌린지 성공률 수정
fix: 챌린지 인증 사진 응답 방식 변경
> feat: 레벨업 기능 구현

- server/wiselife/src/main/java/be/wiselife/dummy/DummyService.java
- server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
- server/wiselife/src/main/java/be/wiselife/image/config/imageConfig.java
- server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
- server/wiselife/src/main/java/be/wiselife/image/service/S3UploadService.java
- server/wiselife/src/main/java/be/wiselife/member/controller/MemberController.java
- server/wiselife/src/main/java/be/wiselife/member/dto/MemberDto.java
- server/wiselife/src/main/java/be/wiselife/member/service/MemberService.java
- server/wiselife/src/main/java/be/wiselife/security/JwtTokenizer.java
- server/wiselife/src/main/resources/application.yml
feat: S3 image setting & member image setting
> feat: S3 image setting & member image setting

- .idea/compiler.xml
- server/wiselife/build.gradle
- server/wiselife/src/main/java/be/wiselife/WiselifeApplication.java
- server/wiselife/src/main/java/be/wiselife/audit/TimeAudit.java
- server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
- server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
- server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
- server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
- server/wiselife/src/main/java/be/wiselife/challenge/repository/ChallengeRepository.java
- server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
- server/wiselife/src/main/java/be/wiselife/challengereview/service/ChallengeReviewService.java
- server/wiselife/src/main/java/be/wiselife/challengetalk/dto/ChallengeTalkDto.java
- server/wiselife/src/main/java/be/wiselife/dummy/DummyService.java
- server/wiselife/src/main/java/be/wiselife/image/config/imageConfig.java
- server/wiselife/src/main/java/be/wiselife/member/dto/MemberDto.java
- server/wiselife/src/main/java/be/wiselife/order/dto/OrderDto.java
- server/wiselife/src/main/java/be/wiselife/schelduler/Scheduler.java
- server/wiselife/src/main/resources/application.yml
feat: challenge 인증가능시간 추가
fix: json responseBody에서 LocalDateTime타입 깨짐 현상 해결
feat: 챌린지 성공률, 챌린지 종료 여부 scheduler 이용해 수정 구현
> feat: scheduler 이용한 챌린지 성공률, 종료여부 수정 구현 및 오류 수정

- server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
- server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
- server/wiselife/src/main/java/be/wiselife/member/dto/MemberDto.java
- server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
- server/wiselife/src/main/java/be/wiselife/member/mapper/MemberMapper.java
- server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepositoryImpl.java
> feat: 다음레벨을 위한 경험치 퍼센 트 구현

- server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
- server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
- server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
- server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
- server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
- server/wiselife/src/main/java/be/wiselife/challengereview/service/ChallengeReviewService.java
- server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
- server/wiselife/src/main/java/be/wiselife/image/service/S3UploadService.java
fix: image upload function "챌린지생성"
> fix: image upload function "챌린지생성"

- server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
- server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
- server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
- server/wiselife/src/main/java/be/wiselife/challengereview/dto/ChallengeReviewDto.java
- server/wiselife/src/main/java/be/wiselife/challengereview/mapper/ChallengeReviewMapper.java
- server/wiselife/src/main/java/be/wiselife/challengetalk/dto/ChallengeTalkDto.java
- server/wiselife/src/main/java/be/wiselife/challengetalk/entity/ChallengeTalk.java
- server/wiselife/src/main/java/be/wiselife/challengetalk/mapper/ChallengeTalkMapper.java
- server/wiselife/src/main/java/be/wiselife/challengetalk/service/ChallengeTalkService.java
- server/wiselife/src/main/java/be/wiselife/dummy/DummyService.java
- server/wiselife/src/main/java/be/wiselife/member/dto/MemberDto.java
- server/wiselife/src/main/java/be/wiselife/member/mapper/MemberMapper.java
- server/wiselife/src/main/java/be/wiselife/memberchallenge/entity/MemberChallenge.java
feat : 마이페이지 내 도전리스트를 도전중과 도전완료로 구분해 서 응답하게 구현
feat : 챌린지의 댓글, 리뷰, 참가자 정보에 멤버 뱃지 정보 출력
> feat : 마이페이지 내 도전리스트를 도전중과 도전완료로 구분해 서 응답하게 구현

- server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
- server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
- server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
- server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
- server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
feat: image function update 챌린지컨트롤러
> feat: image function update 챌린지컨트롤러

- server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
- server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
fix: 챌린지 상세페이지 조회시 이미지 경로 안보이는 오류 해결
> fix: 챌린지 상세페이지 조회시 이미지 경로 안보이는 오류 해결

- server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
- server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
- server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
- server/wiselife/src/main/java/be/wiselife/challengereview/repository/ChallengeReviewRepository.java
- server/wiselife/src/main/java/be/wiselife/challengereview/service/ChallengeReviewService.java
feat: 챌린지 상세조회 시 review도 함께 출력하는 기능 추가
fix: feat: 챌린지=> 챌린지resposneDto의 mulitResponse 버젼 오류 수정
> feat: 챌린지 상세조회 시 review도 함께 출력하는 기능 추가 이외 mapper 오류 수정

- server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
- server/wiselife/src/main/java/be/wiselife/challengereview/controller/ChallengeReviewController.java
- server/wiselife/src/main/java/be/wiselife/challengereview/dto/ChallengeReviewDto.java
- server/wiselife/src/main/java/be/wiselife/challengereview/mapper/ChallengeReviewMapper.java
- server/wiselife/src/main/java/be/wiselife/challengereview/service/ChallengeReviewService.java
- server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
- server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
- server/wiselife/src/main/java/be/wiselife/image/service/S3UploadService.java
feat: review image send logic change
> feat: review image send logic change

- server/wiselife/src/main/java/be/wiselife/member/controller/MemberController.java
- server/wiselife/src/main/java/be/wiselife/member/dto/MemberDto.java
- server/wiselife/src/main/java/be/wiselife/member/mapper/MemberMapper.java
- server/wiselife/src/main/java/be/wiselife/member/service/MemberService.java
- server/wiselife/src/main/java/be/wiselife/security/controller/OauthController.java
- server/wiselife/src/main/resources/application-oauth.yml
> fix: kakao login logic

- server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
- server/wiselife/src/main/java/be/wiselife/challengereview/controller/ChallengeReviewController.java
- server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
- server/wiselife/src/main/java/be/wiselife/member/controller/MemberController.java
- server/wiselife/src/main/java/be/wiselife/member/dto/MemberDto.java
- server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
- server/wiselife/src/main/java/be/wiselife/member/mapper/MemberMapper.java
- server/wiselife/src/main/java/be/wiselife/member/service/MemberService.java
> fix: 맴버 이미지 로직 변경

- server/wiselife/Scripts/kill_process.sh
- server/wiselife/Scripts/remove_before.sh
- server/wiselife/Scripts/run_process.sh
- server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
- server/wiselife/src/main/java/be/wiselife/member/service/MemberService.java
- server/wiselife/src/main/resources/appspec.yml
feat: cicd basic function & fix: member search function
> feat: cicd basic function & fix: member search function

- server/wiselife/build.gradle
- server/wiselife/src/main/java/be/wiselife/WiselifeApplication.java
- server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
- server/wiselife/src/main/java/be/wiselife/dummy/DummyService.java
- server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepositoryImpl.java
- server/wiselife/src/main/resources/application-local.yml
- server/wiselife/src/main/resources/application.yml
> feat: jpa mysql 연동 설정 추가

- server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
- server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
- server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
- server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
- server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
- server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
- server/wiselife/src/main/java/be/wiselife/member/mapper/MemberMapper.java
- server/wiselife/src/main/java/be/wiselife/memberchallenge/entity/MemberChallenge.java
- server/wiselife/src/main/java/be/wiselife/memberchallenge/service/MemberChallengeService.java
- server/wiselife/src/main/java/be/wiselife/schelduler/Scheduler.java
feat: 챌린지 상금 주기적으로 계산 및 상세페이지에 출력
feat: 개인 환급예정금액 계산
> feat: 상금 관련 로직 구현

- server/wiselife/src/main/resources/appspec.yml
> fix: bash codes

- server/wiselife/src/main/java/be/wiselife/member/controller/MemberController.java
- server/wiselife/src/main/java/be/wiselife/member/repository/MemberRepository.java
- server/wiselife/src/main/java/be/wiselife/member/service/MemberService.java
- server/wiselife/src/main/resources/application.yml
> fix: member 검색 pagination 수정

- .github/ISSUE_TEMPLATE/요구사항명-작성시-요구사항명세서-참고----제목----.md
- .github/ISSUE_TEMPLATE/제목----.md
- .github/workflows/gradle.yml
- README.md
> feat: settings on gitActions

- script/deploy.sh
fix: fix the problem of deploy
> fix: fix the problem of deploy

- client/src/App.jsx
- client/src/components/ChallengeDetail/ChallengeDetail.jsx
- client/src/components/ChallengeDetail/ChallengeDetailProgress.jsx
- client/src/components/ChallengeDetail/ImageModal.jsx
- client/src/components/Common/Header.jsx
- client/src/pages/challengeDetailPage.jsx
- client/src/style/ChallengeDetail/ChallengeDetailStyle.jsx
- client/src/style/ChallengeDetailProgress/ChallengeDetailProgressStyle.jsx
- client/src/style/Common/HeaderStyle.jsx
> feat: 로그아웃 구현 및 검색창 수정

- server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
- server/wiselife/src/main/java/be/wiselife/challengereview/service/ChallengeReviewService.java
- server/wiselife/src/main/java/be/wiselife/challengetalk/service/ChallengeTalkService.java
- server/wiselife/src/main/java/be/wiselife/follow/service/FollowService.java
- server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
- server/wiselife/src/main/java/be/wiselife/image/service/S3UploadService.java
- server/wiselife/src/main/java/be/wiselife/member/controller/MemberController.java
- server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
- server/wiselife/src/main/java/be/wiselife/member/service/MemberService.java
- server/wiselife/src/main/java/be/wiselife/memberchallenge/service/MemberChallengeService.java
- server/wiselife/src/main/java/be/wiselife/order/service/OrderService.java
- server/wiselife/src/main/java/be/wiselife/schelduler/Scheduler.java
- server/wiselife/src/main/java/be/wiselife/security/service/OauthService.java
- server/wiselife/src/main/resources/application.yml
> feat : 트랜잭션 추가

- server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
- server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
- server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
- server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
- server/wiselife/src/main/java/be/wiselife/memberchallenge/service/MemberChallengeService.java
- server/wiselife/src/main/java/be/wiselife/order/controller/OrderController.java
- server/wiselife/src/main/java/be/wiselife/order/service/OrderService.java
- server/wiselife/src/main/resources/application.yml
fix : 생성할때 결제, 참가할때 결제 후 챌린지 생성, 참가 되게 변경
fix: 챌린지 탈퇴 버튼 두번 누르면 예외 처리
fix: 중복가입은 프론트에 요청
> fix : 생성할때 결제, 참가할때 결제 후 챌린지 생성, 참가 되게 변경

- server/wiselife/src/main/resources/application-aws.yml
> fix: 카카오 환경변수 git actions에 추가

- server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
- server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
- server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
- server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
- server/wiselife/src/main/java/be/wiselife/memberchallenge/service/MemberChallengeService.java
- server/wiselife/src/main/java/be/wiselife/order/controller/OrderController.java
- server/wiselife/src/main/java/be/wiselife/order/service/OrderService.java
- server/wiselife/src/main/java/be/wiselife/quesrydslrepo/QuerydslRepositoryImpl.java
- server/wiselife/src/main/java/be/wiselife/security/SecurityConfiguration.java
- server/wiselife/src/main/java/be/wiselife/security/dto/LoginDto.java
- server/wiselife/src/main/java/be/wiselife/security/service/OauthService.java
- server/wiselife/src/main/resources/application.yml
> fix : 결제 충전형태로 변경

- server/wiselife/src/main/resources/logback-spring.xml
> fix: setting

- server/wiselife/src/main/java/be/wiselife/challengereview/entity/ChallengeReview.java
- server/wiselife/src/main/java/be/wiselife/schelduler/Scheduler.java
- server/wiselife/src/main/java/be/wiselife/schelduler/SchedulerConfig.java
> fix: scheduler 주기 변동

- server/wiselife/src/main/java/be/wiselife/challenge/controller/ChallengeController.java
- server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
- server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
- server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
- server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
- server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
- server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
- server/wiselife/src/main/java/be/wiselife/member/controller/MemberController.java
- server/wiselife/src/main/java/be/wiselife/memberchallenge/service/MemberChallengeService.java
- server/wiselife/src/main/java/be/wiselife/schelduler/Scheduler.java
- server/wiselife/src/main/resources/application.yml
fix : 챌린지 참가/탈퇴시 포인트 변경되게 수정, 챌린지내 최소인원, 최대인원, 최소 참가금 벨리데이션 추가
fix: 챌린지 설명, 챌린지 인증사진 설명 varchar크기 변경
> ix : 챌린지 참가/탈퇴시 포인트 변경되게 수정, 챌린지내 최소인원, 최대인원, 최소 참가 금 벨리데이션 추가

- server/wiselife/src/main/java/be/wiselife/challenge/service/ChallengeService.java
- server/wiselife/src/main/java/be/wiselife/schelduler/Scheduler.java
- server/wiselife/src/main/resources/application.yml
fix: 스케줄러 주기 수정 및 progressRate 1 넘는 경우 예외처리 수정
> fix: 스케줄러 주기 수정 및 progressRate 1 넘는 경우 예외처리 수정

- server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
- server/wiselife/src/main/resources/application.yml
> fix: 챌린지 설명, 챌린지 인증설명 칼럼 속성변경

- server/wiselife/src/main/java/be/wiselife/WiselifeApplication.java
- server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
- server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
- server/wiselife/src/main/resources/application.yml
- server/wiselife/src/main/resources/logback-spring.xml
feat: demoday 깜짝이벤트 생성
fix: demoday 이벤트 챌린지라도 시작일자 이전 인증은 인증 못하게 로직 수정
> feat: demoday용 깜짝이벤트 챌린지 로직 추가

- server/wiselife/src/main/java/be/wiselife/challenge/dto/ChallengeDto.java
- server/wiselife/src/main/java/be/wiselife/challenge/entity/Challenge.java
- server/wiselife/src/main/java/be/wiselife/challenge/mapper/ChallengeMapper.java
- server/wiselife/src/main/java/be/wiselife/exception/ExceptionCode.java
- server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
- server/wiselife/src/main/java/be/wiselife/member/entity/Member.java
- server/wiselife/src/main/java/be/wiselife/schelduler/Scheduler.java
- server/wiselife/src/main/resources/application.yml
fix : 챌린지 인증사진 동일 시간대 등록시 최근 등록한걸로 수정되게 수정
> fix : 챌린지 인증사진 동일 시간대 등록시 최근 등록한걸로 수정되게 수정

- server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
fix: demoday용 챌린지가 모든 로직 타는 것 수정
> fix: demoday용 챌린지가 모든 로직 타는 것 수정

- server/wiselife/src/main/java/be/wiselife/image/service/ImageService.java
- server/wiselife/src/main/resources/application.yml
fix: merge 후 챌린지내 멤버 금일 인증횟수 표시 구현
> fix: merge 후 챌린지내 멤버 금일 인증횟수 표시 구현

- server/wiselife/src/main/java/be/wiselife/aop/DiscordWebhook.java
- server/wiselife/src/main/resources/application-aws.yml
> fix: discord problem

- server/wiselife/src/main/java/be/wiselife/order/service/OrderService.java
- server/wiselife/src/main/resources/application-aws.yml
> fix : secret text issues
